name: "💡 Feature Request"
description: "Choose this to Request a New Feature"
title: "💡 [FEATURE] - <title>"
labels: [
  "enhancement"
]

body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide an explanation of the feature
      placeholder: Describe your Feature Request
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If Applicable, add Screenshots to help us Visualise the Feature
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false


